In [12]:
#for checking numpy version
import numpy as np
#np.__version__

# Creating an Array

In [13]:
lst = [1,2,3,4,5]
ar1 = np.array([1,2,3,4,5],ndmin=6)
ar1
#it takes only same type of data type in the array if we give another data type it convert whole array into same data type


array([[[[[[1, 2, 3, 4, 5]]]]]])

In [14]:
#if we want to create an array in range
ar2 =np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [16]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr5 = np.linspace(1,20,50)
arr5
#here first two elements reprsent the range in which the numbers came and last element reprsent the count of numbers

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [18]:
arr6 = np.arange(30).reshape(5,6)
arr6
#if we want to convert the 2d array into 1d array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
arr7 = np.random.randint(1,100,10)
#arr7 = np.random.random(10)
arr7
#random is a module which is used to generate the random values 

array([ 2, 46, 14, 28, 22, 51, 15, 58, 76, 57], dtype=int32)

In [20]:
#for float values
arr8 = np.random.random(10)
arr8 

array([0.75904907, 0.32436666, 0.21145742, 0.77080341, 0.27265658,
       0.86097298, 0.30462346, 0.42978137, 0.68444025, 0.63392802])